[package]
name = "bit_streamer"
version = "0.1.0"
authors = ["JakeHuneau <jakehuneau@yahoo.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/JakeHuneau/bitStreamer"
description = "Stream bits using a BufReader and BufWriter"

[dependencies]
